#! /bin/bash

if ! command -v jq >/dev/null; then
  echo "You need to install the 'jq' package.";
  exit 1
fi

if ! command -v busybox >/dev/null; then
#if ! command -v python >/dev/null && ! command -v busybox >/dev/null; then
  echo "You need to have  busybox installed.";
  #echo "You need to have either python or busybox installed.";
  exit 1
fi

# configuration
HOST=127.0.0.1
PORT=8000

# create empty logfile
rm -f logfile.log
touch logfile.log

# kill webserver process when script has ended
_term() {
  echo "Shutting down server..."
  kill -TERM "$SERVER_PID" 2>/dev/null
}
trap _term TERM INT

# start webserver
#if command -v python3; then
#  python3 -m http.server --cgi $PORT &
#elif command -v python2; then
#  python2 -m CGIHTTPServer $PORT &
#elif command -v busybox >/dev/null ; then
  busybox httpd -vv -f -p $HOST:$PORT &
#fi
SERVER_PID=$!

echo "Started HTTP server. To access EXcite tools, open http://$HOST:$PORT/index.html"
wait "$SERVER_PID"