#! /bin/bash

# requirements:
# - busybox (sudo apt install busybox)
# - jq (sudo apt install jq)

# configuration
HOST=127.0.0.1
BUSYBOX_PORT=8000

# create empty logfile
rm -f logfile.log
touch logfile.log

# kill webserver process when script has ended
_term() {
  echo "Shutting down servers..."
  kill -TERM "$BUSYBOX_PID" 2>/dev/null
}
trap _term TERM INT

# start webserver
busybox httpd -f -p $HOST:$BUSYBOX_PORT &
BUSYBOX_PID=$!
echo "Started HTTP server at http://$HOST:$BUSYBOX_PORT/index.html."
wait "$BUSYBOX_PID"