#! /bin/bash

filename=$(basename -- "$filepath_uplfile")
extension="${filename##*.}"
filename_no_ext="${filename%.*}"

echo "Access-Control-Allow-Origin: *\n"
#rm -f Data/*/*
#rm -f Data/1-pdfs/.gitkeep
#cat $filepath_uplfile > Data/1-pdfs/${filename_no_ext}.pdf
#docker run --rm -v $(pwd):/app excite_toolchain layout >> logfile.log
#docker run --rm -v $(pwd):/app excite_toolchain exparser >> logfile.log
#touch Data/1-pdfs/.gitkeep
resultfile="Data/3-refs_seg_dict/${filename_no_ext}.csv"
if [[ -f "$resultfile" ]] ; then
    echo "Content-Type: application/javascript\n"
    echo "Content-Disposition: attachment; filename='${filename_no_ext}.json'"
    echo
    refs_as_json=$(cat "$resultfile" | sed -e 's/}$/},/g')
    refs_as_json="[${refs_as_json%?}]"
    echo "$refs_as_json" > "Data/3-refs_seg_dict/${filename_no_ext}.json"
else
    echo
    echo '{"error":"An error occurred!"}'
fi
