#! /bin/bash
echo "Content-type: application/json"
echo

HOME_DIR=$(realpath ..)
DATA_DIR="$HOME_DIR/Data"
LOGFILE=$HOME_DIR/logfile.log

parts=(${QUERY_STRING//:/ })
fileId=${parts[0]}
filename=${parts[1]}
extension="${filename##*.}"
filename_no_ext="${filename%.*}"

if [[ "$fileId" == "" ]] || [[ "$filename" == "" ]]; then
  echo '{"error":"No file information given"}'
  exit 1
fi

rm -f $DATA_DIR/*/*
rm -f $DATA_DIR/1-pdfs/.gitkeep
mv /tmp/$fileId $DATA_DIR/1-pdfs/$filename

docker run --rm -v $HOME_DIR:/app excite_toolchain layout >> $LOGFILE
docker run --rm -v $HOME_DIR:/app excite_toolchain exparser >> $LOGFILE

touch $DATA_DIR/1-pdfs/.gitkeep 2> /dev/null

layoutfile="$DATA_DIR/2-layouts/${filename_no_ext}.csv"
refsfile="$DATA_DIR/3-refs/${filename_no_ext}.csv"

if [[ -f "$layoutfile" ]] && [[ -f "$refsfile" ]]; then
    echo "{\"layout\":$(cat $layoutfile | jq -Rs 'split("\n")'), \"refs\":$(cat $refsfile | jq -Rs 'split("\n")')}"
else
    echo '{"error":"An error occurred!"}'
fi
